export const components = {
  Accordion: "accordion",
  Alert: "alert",
  AspectRatio: "aspect-ratio",
  Avatar: "avatar",
  Badge: "badge",
  Box: "box",
  Button: "button",
  Card: "card",
  Carousel: "carousel",
  Checkbox: "checkbox",
  Dialog: "dialog",
  ListBox: "list-box",
  Progress: "progress",
  Radio: "radio",
  Separator: "separator",
  Skeleton: "skeleton",
  Switch: "switch",
  Tabs: "tabs",
  Tag: "tag",
  TextArea: "text-area",
  TextField: "text-field",
  Toggle: "toggle",
  Typography: "typography",
} as const;
