name: Preview

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🥡 Setup PNPM
        uses: pnpm/action-setup@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Storybook Preview
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./storybook-static
          destination: pr-previews/${{ github.event.pull_request.number }}

  deploy:
    needs: build-and-preview
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Preview to GitHub Pages
        uses: actions/deploy-pages@v1

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Preview available: [Storybook Preview](https://mauroreisvieira.github.io/stewed/pr-previews/${{ github.event.pull_request.number }})
