name: Storybook

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: 🥡 Setup PNPM 9
              uses: pnpm/action-setup@v4
              with:
                version: 9

            - name: 🟢 Setup Node
              uses: actions/setup-node@v4
              with:
                cache: pnpm
                node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Build Storybook
              run: pnpm run build-storybook

            - name: Upload Storybook to GitHub Pages
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./storybook-static

    deploy:
        needs: build-and-deploy
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
